version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo hola! > sayhi.txt
      - echo oi! >> sayhi.txt
      - echo halo! >> sayhi.txt
      - echo ciao! >> sayhi.txt
      - cat sayhi.txt
      - echo $CODEBUILD_SRC_DIR
      - cp $CODEBUILD_SRC_DIR/README.md /tmp/test.md
artifacts: 
  files: 
    - sayhi.txt
