version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - echo hola! > sayhi.txt
      - echo oi! >> sayhi.txt
      - echo halo! >> sayhi.txt
      - echo ciao! >> sayhi.txt
      - cat sayhi.txt
      - echo $CODEBUILD_WEBHOOK_BASE_REF #this is a temporary test feel free to erase it.
artifacts: 
  files: 
    - sayhi.txt
