---
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'happy-${AWS::AccountId}-${AWS::Region}'

Outputs:
  Parameter:
    Value: !Ref S3Bucket
